### ISSUE TITLE
Favouriting bus stops without major label crashes app

### ISSUE THREAD

**Issue by rhysm94** [smallstoneapps/uk-transport#8]
Attempting to favourite the bus stops

> **NE-bound**
> Promenade East

or

> **SE-bound**
> Promenade East

works without an issue, successfully pinning the application to the top of my Bus Stops.
However, attempting to favourite the bus stop

> Cefn Coed Crescent

instead results in the application crashing.

Unfortunately, the majority of the bus stops I use don't have any major label, just the one line.
I've attempted re-installing the application, resetting my Pebble etc. but nothing seems to fix the problem.

![img_1352](https://cloud.githubusercontent.com/assets/11096937/6697733/7b19639c-ccea-11e4-8146-1d932c226e8a.jpg)

**Comment by jamesweech** [comment]
+1 same for me here, Stops me using the app

**Comment by matthewtole** [comment]
I think I have fixed the problem, could one or both of you try out the PBW at this link and tell me if it works for you? 

https://www.dropbox.com/s/90tp5tx6rqo3dl2/uk-transport_1.7.pbw?dl=0

Thanks!

**Comment by jamesweech** [comment]
@matthewtole Trying now

**Comment by jamesweech** [comment]
@matthewtole Works fine thanks, [Made a separate issue for the other thing]

**Comment by rhysm94** [comment]
Ah, that's fantastic!
It works great for me now :)
Thank you!

**Comment by matthewtole** [comment]
Thanks @jamesweech and @rhysm94, I'll publish the update shortly. Thanks for the feature suggestion as well, I will look into it.
